# Generated by Django 2.1.5 on 2019-05-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('wbcore', '0001_initial'),
        ('schedule', '0011_event_calendar_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Event')),
                ('title_de', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('teaser', models.TextField(blank=True, max_length=120)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True, null=True)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Gallery')),
            ],
            options={
                'get_latest_by': ['start'],
            },
            bases=('schedule.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ManyToManyField(to='wbcore.Host'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Photo'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wbcore.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='projects',
            field=models.ManyToManyField(blank=True, to='wbcore.Project'),
        ),
    ]
